[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Wine-Scoring"
version = "0.1.0"
authors = [{name = "gnimpf", email = "nope@nope"}]
dynamic = ["version", "description"]
